### ISSUE TITLE
Odd behavior in statick_tool.exceptions.filter_file_exceptions

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#48] opened 2019-01-18 15:39 UTC
While working on #47, I noticed that my issues weren't getting printed. Further investigation showed that they were getting caught by the "remove issues which contain */statick_output/*" filter, even though the files in question weren't in statick_output. The issue appears to trace to line 60:
`rel_path = os.path.relpath(issue.filename, package.path)`
Given an input of `Test.java` and `/home/creffett/workspace/statick/test`, rel_path is set to `../statick_output/test-sei_cert/Test.java` (because the relative path from package.path to a file named `Test.java` in the current directory is `../statick_output/test-sei_cert/Test.java`), which is the wrong path and doesn't exist. I'm not sure what the intended behavior of this line is - I'm guessing it should be os.path.join, but I'm not sure.

**Comment by tdenewiler** [comment] 2019-01-19 06:58
I looked at this for a while, and I think the issue is that the code to apply exceptions is expecting the tool plugins to output issues that have an absolute path to the file containing the issue. I tried to get findbugs to include the absolute file path in its output, but I was not able to do so.

In the simple case where you have <package>/Test.java and compile that, then you can prepend `package.path/` to `match.group(3)` when creating the issue in the findbugs plugin. That scenario ended up with a relative path that worked in the exceptions file, and preserving all the issues in the final report. However, this approach fails if the Test.java file is in a subdirectory of <package>. Note, I used your Test.java file from #47.

There could be a way to pass in the `files` variable to `parse_output`. The `files` variable has absolute paths. Then the output of findbugs, which gives only the filename without any sort of path, could be searched to get the absolute path. That would fail if multiple subdirectories contained a file with the same name. Another approach could be to scan and parse the output of a single file at a time. I don't know if that would work, or if it would take a long time even if it did work.

**Comment by creffett** [comment] 2019-01-21 13:52
Ahhhh, I get it now. I'll take a look at options to fix it. Is it documented anywhere that an absolute path is expected there? If not, that would be helpful for future plugin authors.

**Comment by tdenewiler** [comment] 2019-01-21 21:59
I didn't write that part of the tool and found a hint in the Users Guide in the section discussing how to use `exceptions.yaml`. I agree that additional documentation in the source code and clarifying in the Users Guide would be helpful for future users and authors.

**Comment by creffett** [comment] 2019-01-22 15:21
So I dug into this a little more, and part of the issue is that findbugs is smart enough to correlate the .class file to a .java file, but we currently don't do that matchup. Also, only the XML output of findbugs has a full source path, and that's only if the file is using well-defined package paths (e.g. it understands that "package com.github.package" should translate to a path of com/github/package). I'm okay punting this issue for a little while - I think that in order to really make use of findbugs, we'd need a maven/gradle discovery plugin in order to guarantee that compiled java files are available.

**Comment by creffett** [comment] 2019-01-23 21:12
Maybe as a band-aid, we could make use of https://docs.python.org/3/library/os.path.html#os.path.isabs, and only apply path exceptions to absolute paths? Or something like that.

**Comment by denewiler** [comment] 2020-01-25 16:11
The workaround has been sufficient so far. Closing for now, but I am open to a more elegant solution in the future.

**Closed by denewiler** 2020-01-25 16:11 UTC
Labels: bug
